---
- name: Ensure GLPI is not already installed - URL check
  ansible.builtin.uri:
    url: "{{ glpi_url }}"
    status_code: 200
    return_content: true
    validate_certs: false
  register: _glpi_install_check
  failed_when: false

- name: Assert GLPI installation
  ansible.builtin.debug:
    msg:
      - "GLPI is already installed on {{ glpi_url }}."
      - "If you want to upgrade or reconfigure GLPI, please use the appropriate playbooks."
      - "Aborting installation."
  when: _glpi_install_check.status == 200 and "Login" in _glpi_install_check.content

- name: Install GLPI
  when: _glpi_install_check.status != 200 or not "Login" in _glpi_install_check.content
  block:
    - name: Confirm Reinstall - overrides database
      ansible.builtin.pause:
        prompt: "This install task is meant to run for primo-installs, as it will erase all GLPI data. Do you want to continue with the installation? (yes/no)"
      register: _glpi_install_confirm

    - name: Install using CLI
      become: true
      ansible.builtin.command: |
        bin/console db:install --no-interaction \
        --db-host={{ glpi_db_host }} \
        --db-name={{ glpi_db_name }} \
        --db-user={{ glpi_db_user }} \
        --db-password={{ glpi_db_password }} \
        --db-port={{ glpi_db_port }} \
        --reconfigure \
        --force \
        --no-telemetry
      args:
        chdir: /var/www/html/glpi
      changed_when: false
      register: _glpi_install_result
      when:
        - _glpi_install_confirm.user_input | lower == 'yes'

    - name: Check GLPI liveness
      ansible.builtin.uri:
        url: "{{ glpi_url }}"
        return_content: true
        status_code: 200
        validate_certs: false
      register: _glpi_post_install_check
      retries: 5
      delay: 10
      until: _glpi_post_install_check.status == 200 and not "Login" in _glpi_post_install_check.content
