---
- name: Download official archive
  ansible.builtin.get_url:
    url: "https://github.com/glpi-project/glpi/releases/download/{{ glpi_version }}/glpi-{{ glpi_version }}.tgz"
    dest: "/tmp/glpi-{{ glpi_version }}.tgz"
    mode: '0644'
  register: _glpi_download

- name: Check if GLPI is installed - Directory check
  ansible.builtin.stat:
    path: /var/www/html/glpi
  register: _glpi_dir_check

- name: Check if GLPI is installed - DB check
  become: true
  ansible.builtin.command: |
    su www-data -s /bin/bash -c "bin/console db:check --quiet"
  args:
    chdir: /var/www/html/glpi
  register: _glpi_install_check
  failed_when: false
  changed_when: false
  when: _glpi_dir_check.stat.exists

- name: Install
  ansible.builtin.include_tasks: install.yml
  when: not _glpi_dir_check.stat.exists

- name: Upgrade
  ansible.builtin.include_tasks: upgrade.yml
  when: _glpi_dir_check.stat.exists and _glpi_install_check.rc == 0 and _glpi_download is changed
