FROM ubuntu:22.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
    apt-get install -y openssh-server mysql-server sudo && \
    useradd -m -s /bin/bash ubuntu && \
    echo 'ubuntu ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers && \
    mkdir /var/run/sshd

    RUN mkdir -p /home/ubuntu/.ssh && \
    chown ubuntu:ubuntu /home/ubuntu/.ssh && \
    chmod 700 /home/ubuntu/.ssh

COPY authorized_keys /home/ubuntu/.ssh/authorized_keys
RUN chown ubuntu:ubuntu /home/ubuntu/.ssh/authorized_keys && \
    chmod 600 /home/ubuntu/.ssh/authorized_keys

COPY mysql-init.sql /docker-entrypoint-initdb.d/
RUN service mysql start && \
    mysql < /docker-entrypoint-initdb.d/mysql-init.sql

EXPOSE 22 3306

CMD ["/bin/bash", "-c", "service mysql start && /usr/sbin/sshd -D"]