CREATE DATABASE IF NOT EXISTS glpi;
CREATE USER IF NOT EXISTS 'glpi'@'%' IDENTIFIED BY 'glpi';
CREATE USER IF NOT EXISTS 'glpi'@'localhost' IDENTIFIED BY 'glpi';
GRANT ALL PRIVILEGES ON glpi.* TO 'glpi'@'%';
GRANT ALL PRIVILEGES ON glpi.* TO 'glpi'@'localhost';
FLUSH PRIVILEGES;