- name: CI
  run-name: CI
  on: [push, pull_request]
  jobs:
    ci:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v2

      - name: ansible-lint
        uses: ansible/ansible-lint@main
        with:
          args: -c .ansible-lint.yml
