name: CI
run-name: CI
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  ansible-lint:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Ansible Lint
        uses: ansible/ansible-lint@main
        with:
          args: -c .ansible-lint.yml

  markdown-lint:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Markdown lint
        uses: DavidAnson/markdownlint-cli2-action@v20
        with:
          globs: '**/*.md'
