name: CI
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  ansible-lint:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Ansible Lint
        uses: ansible/ansible-lint@main

  markdown-lint:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Markdown lint
        uses: DavidAnson/markdownlint-cli2-action@v20
        with:
          globs: '**/*.md'

  test:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Start services with Compose
        run: |
          docker compose -f tests/docker-compose.yml up --build -d

      - name: Install Ansible and dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ansible

      - name: Setup SSH agent for Ansible
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: "${{ secrets.ANSIBLE_CI_SSH_PRIVATE_KEY }}"

      - name: Run Ansible tests
        run: |
          ansible-playbook -i tests/inventory tests/ubuntu-22.04.yml
